TZ_NAMES = [
    {"Samoa": "Pacific/Samoa"},
    {"Hawaii": "Pacific/Honolulu"},
    {"Marquesas Islands": "Pacific/Marquesas"},
    {"Alaska": "America/Anchorage"},
    {"Baja California": "America/Tijuana"},
    {"Pacific Time (US & Canada)": "America/Los_Angeles"},
    {"Chihuahua,Mazatlan": "America/Chihuahua"},
    {"Arizona": "America/Phoenix"},
    {"Mountain Time (US & Canada)": "America/Denver"},
    {"Central Time (US & Canada)": "America/Chicago"},
    {"Central America": "America/Guatemala"},
    {"Guadalajara,Mexico City, Monterrey": "America/Mexico_City"},
    {"Saskatchewan": "America/Regina"},
    {"Bogota, Lima, Quito": "America/Bogota"},
    {"Eastern Time (US & Canada)": "America/New_York"},
    {"Indiana (East)": "America/Indianapolis"},
    {"Caracas": "America/Caracas"},
    {"Atlantic Time (Canada)": "America/Halifax"},
    {"Asuncion": "America/Asuncion"},
    {"Cuiaba": "America/Cuiaba"},
    {"Santiago": "America/Santiago"},
    {"Georgetown, La Paz, Manaus, San Juan": "America/La_Paz"},
    {"Newfoundland": "America/St_Johns"},
    {"Buenos Aires": "America/Buenos_Aires"},
    {"Brasilia": "America/Sao_Paul"},
    {"Cayenne, Fortaleza": "America/Cayenne"},
    {"Montevideo": "America/Montevideo"},
    {"Greenland": "America/Godthab"},
    {"Azores": "Atlantic/Azores"},
    {"Cape Verde Is.": "Atlantic/Cape_Verde"},
    {"Casablanca": "Africa/Casablanca"},
    {"Monrovia,Reykjavik": "Atlantic/Reykjavik"},
    {"Greenwich Mean Time : Dublin,Edinburgh,Lisbon, London": "Europe/London"},
    {"Sarajevo,Skopje, Warsaw, Zagreb": "Europe/Warsaw"},
    {"West Central Africa": "Africa/Lagos"},
    {"Belgrade,Bratislava, Budapest, Ljubljana, Prague": "Europe/Budapest"},
    {"Brussels, Copenhagen,Madrid, Paris": "Europe/Paris"},
    {"Amsterdam,Berlin, Bern, Rome,Stockholm, Vienna": "Europe/Berlin"},
    {"Harare, Pretoria": "Africa/Johannesburg"},
    {"Damascus": "Asia/Damascus"},
    {"Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius": "Europe/Kiev"},
    {"Windhoek": "Africa/Windhoek"},
    {"Minsk": "Europe/Minsk"},
    {"Athens,Bucharest, Istanbul": "Europe/Istanbu"},
    {"Amman": "Asia/Amman"},
    {"Beirut": "Asia/Beirut"},
    {"Jerusalem": "Asia/Jerusalem"},
    {"Cairo": "Africa/Cairo"},
    {"Kuwait, Riyadh": "Asia/Riyadh"},
    {"Moscow, St. Petersburg, Volgograd": "Europe/Moscow"},
    {"Baghdad": "Asia/Baghdad"},
    {"Nairobi": "Africa/Nairobi"},
    {"Tehran": "Asia/Tehran"},
    {"Port Louis": "Indian/Mauritius"},
    {"Tbilisi": "Asia/Tbilisi"},
    {"Baku": "Asia/Baku"},
    {"Yerevan": "Asia/Yerevan"},
    {"Abu Dhabi, Muscat": "Asia/Dubai"},
    {"Kabul": "Asia/Kabul"},
    {"Yekaterinburg": "Asia/Yekaterinburg"},
    {"Islamabad,Karachi": "Asia/Karachi"},
    {"Tashkent": "Asia/Tashkent"},
    {"Chennai, Kolkata, Mumbai,New Delhi": "Asia/Calcutta"},
    {"Sri Jayawardenepura": "Asia/Colombo"},
    {"Kathmandu": "Asia/Katmandu"},
    {"Dhaka": "Asia/Dhaka"},
    {"Novosibirsk": "Asia/Novosibirsk"},
    {"Astana": "Asia/Almaty"},
    {"Yangon (Rangoon)": "Asia/Rangoon"},
    {"Krasnoyarsk": "Asia/Krasnoyarsk"},
    {"Bangkok, Hanoi,Jakarta": "Asia/Bangkok"},
    {"Ulaanbaatar": "Asia/Ulaanbaatar"},
    {"Perth": "Australia/Perth"},
    {"Taipei": "Asia/Taipei"},
    {"Kuala Lumpur,Singapore": "Asia/Singapore"},
    {"Beijing,Chongqing,Hong Kong, Urumqi": "Asia/Shanghai"},
    {"Irkutsk": "Asia/Irkutsk"},
    {"Pyongyang": "Asia/Pyongyang"},
    {"Eucla": "Australia/Eucla"},
    {"Seoul": "Asia/Seoul"},
    {"Osaka,Sapporo, Tokyo": "Asia/Tokyo"},
    {"Yakutsk": "Asia/Yakutsk"},
    {"Darwin": "Australia/Darwin"},
    {"Adelaide": "Australia/Adelaide"},
    {"Hobart": "Australia/Hobart"},
    {"Vladivostok": "Asia/Vladivostok"},
    {"Guam, Port Moresby": "Pacific/Port_Moresby"},
    {"Brisbane": "Australia/Brisbane"},
    {"Canberra,Melbourne, Sydney": "Australia/Sydney"},
    {"Lord Howe Island": "Australia/LHI"},
    {"Magadan, Solomon Is.,New Caledonia": "Asia/Magadan"},
    {"Fiji": "Pacific/Fiji"},
    {"Petropavlovsk-Kamchatsky": "Asia/Kamchatka"},
    {"Auckland, Wellington": "Pacific/Auckland"},
    {"Chatham Islands": "Pacific/Chatham"},
    {"Phoenix Islands, Tokelau, Tonga": "Pacific/Enderbury"},
    {"Line Islands": "Pacific/Kiritimati"},
]
